### ISSUE TITLE
Research vendor applications: Asana, Mizito, and OpenProject

### ISSUE THREAD

**Issue by atareversei** [basliqlabs/qwest-docs#10]
**[EN]**  
Sign up in these applications:
1. Asana
2. Mizito
3. OpenProject

and try using them and exploring their features. As you are using these pieces of software, try taking notes about their:
- UI
- UX
- Flows of Processes
- Systems (the app might be able to be broken in multiple logical parts: e.g. task management, messaging, financial features). Each application might have different systems and features e.g. In GitHub you can reference an `issue` or `pull request` or parts of codebase in a task which is not available in most other applications. 
- Features of each logical part (e.g. features available in task management)
- Terminology

---

**[FA]**
در برنامه‌های زیر ثبت نام کن:
1. Asana
2. Mizito
3. OpenProject

و اونارو به عنوان کسی که میخواد پروژه رو مدیریت کنه استفاده کن تا بتونی امکاناتی که برنامه در اختیار مدیر پروژه قرار میده رو ببینی و اکتشاف کنی. سعی کن وقتی داری استفاده میکنی موارد زیر رو یادداشت کنی:
1. یو آی
4. یو ایکس
5. اینکه جریان کلی روندها توی برنامه چطوریه (مثلا ثبت نام کردی بعدش چی شد، یا پروژه ایجاد کردی بعدش چی شد)
6. سیستم‌های متفاوت رو تشخیص بده. اکثر برنامه‌هایی که مشخص شده، دارای بخش‌های متفاوتی هستن. مثلا ممکنه یکی مدیریت تسک + حسابداری + پیام‌رسانی داشته باشه، ممکنه یکی دیگه مدیریت تسک + مدیریت پروژه داشته باشه. هر تقسیم بندی‌ای که به نظرتون منطقی اومد رو بنویسید.
7. برای هر بخش که تو مورد قبلی مشخص کردیم باید تمام فیچرهاشو در بیاریم و مستند کنیم.
8. ترمینولوژی (واژگان مورد استفاده)

**Comment by MirHosseinAmiriNotash** [comment]
[FA]  

# Mizito  
میزیتو یک ابزار مدیریت پروژه ایرانی هست و من می خوام بررسی بکنم که چه ویژگی ها و امکاناتی رو به کاربران ارائه می دهد.  

## Login & Signup
فرایند ثبت نام ساده هست و با گرفتن شماره موبایل و کد تایید انجام می شود و در ادامه اطلاعاتی مثل نام و نام خانوادگی،پسورد و نام شرکت یا تیم را از ما درخواست می کند که در تصویر زیر می بینیم و با تکمیل این اطلاعات ثبت نام انجام می شود :  

![signup](https://github.com/user-attachments/assets/d8bff7e4-bc60-46a0-9f4a-970391c4978d)


در مرحله بعد از ما می خواد که اگر همکاری داریم به میزکارمون اضافه بکنیم :  
 
![add](https://github.com/user-attachments/assets/cf07e117-cb6c-4880-9121-d90dd95cdbbe)

بعد از تمام شدن ثبت نام می تونیم نمای کلی از نرم افزار رو ببینیم :  

![FirstView](https://github.com/user-attachments/assets/eaaf0bd7-8339-45eb-ba3f-c5891d938e1b)
## UI
از لحاظ UI من از صفحه لاگین خوشم اومد انیمیشن داشت و جذاب ترش کرده که می تونیم توی این عکس قسمت لاگین رو ببینیم :  

![LoginPage](https://github.com/user-attachments/assets/29f3b584-7710-40a5-ba5a-d58b3d5a14dc)
اینطوریه که سمت چپ یه اسلایدره و عوض میشه و هرکدوم یک انیمیشنی داره از این بخشش خوشم اومد.  
ولی رنگ هایی که توی خود محیط استفاده شده خوشم نیومد که بیشتر از رنگ قرمز مایل به نارنجی استفاده شده معمولا از رنگ قرمز توی جاهایی مثل فروشگاه ها رستوران ها استفاده میشه رنگ قرمز خاصیتی که داره احساس گرسنگی ایجاد می کنه مثلا به شما یک نوشابه کوکاکولا و یک نوشابه پپسی بدن به احتمال زیاد شما کوکاکولا رو برمیدارید چون رنگش قرمزه ولی این توی جاهایی مثل رستوران استفاده میشه و توی جاهایی که مربوط به تکنولوژیه از رنگ هایی مثل آبی که حس اعتماد میده و برای تکنولوژی استفاده میشه یا رنگ هایی مثل سبز و بنفش هم میتونه برای تکنولوژی استفاده بشه و این رنگی که انتخاب کرده به من حس خوبی نمیده و به من حس یک محیط حرفه ای رو نمیده.  
اگرم قراره از رنگ قرمز استفاده بکنه لاقل از این قرمز نه یکم عجیبه رنگش مثلا می تونست تیره تر باشه مثلا می تونه این رنگ باشه :   

![RedPalette](https://github.com/user-attachments/assets/6731b4bd-4e7d-413a-94a9-139521079dbf)
## UX
از لحاظ UX بازم مرتبط با رنگ می تونست یک بخشی بزاره که بتونیم رنگ ها رو شخصی سازی بکنیم و عوضشون بکنیم و فقط یک سری بک گراند های محدود گذاشته که فقط اونارو می تونیم عوض کنیم :  

![changeBG](https://github.com/user-attachments/assets/4630335d-b44f-474f-a2b0-5c58f71a9418)

حتی این امکان نیست که بک گراندی که خودمون می خوایم و مثلا توی سیستممون هست انتخاب بکنیم.  
یک مورد دیگه اینکه حالت دارک مود نداره و بعضی آیکون ها یک سایه نئونی مانند ، هم رنگ خود آیکون دارن که اگه دارک مود بود و فعالش می کردیم هم محیط جذاب تر می شد و هم آیکون جلوه بهتری میدادن مثلا آیکون پیام ها یک سایه هم رنگ خودش داره فکر کنم وقتی مثلا پیامی داشته باشیم اون سایه نمایش داده میشه چون فقط این آیکون سایه داره و بقیه نه. این به نظرم نکته خوبیه و یک قسمتی رو با این کار bold می کنه که به چشم بیاد مثلا اگر پیامی رو نخونده باشیم با این کار بیشتر به چشم میاد که پیامی هست که نخوندم:  

![icon](https://github.com/user-attachments/assets/f66b5369-b529-4bfe-893c-382c3ae1f9ed) 

ایجاد تسک یا وظیفه سادس و خوبه و موقع ایجاد چیز هایی مثل عنوان وظیفه ، توضیحاتی در مورد وظیفه ، اضافه کردن برچسب ، اضافه کردن چک لیست(که می تونه یک تسک رو به چند قسمت تقسیم بکنه و خوبه) ، امکان اضافه کردن زمان یادآوری (به نظرم ویژگی خوبیه)، محول کردنه تسک به یک فرد، و انتخاب دسته بندی پروژه :  

![Create Task](https://github.com/user-attachments/assets/f2311150-0f3e-48e5-adeb-e307429c5ab1)
ایجاد پروژه ساده هست و فقط نام پروژه رو از ما می خواد:  

![Create Project](https://github.com/user-attachments/assets/642ee6c7-be57-42b9-9a4b-f71ab62fe7b0)
## Features 
---
### Security  
  در بخش تنظیمات حساب کاربری یه بخش امنیت هست که اونجا نشون میده که چه کسانی در چه ساعتی به اکانت شما وارد شدن و این به نظرم ویژگی خوبیه :  

  ![Loginlog](https://github.com/user-attachments/assets/3487c38c-1a3e-49e6-b66f-1917506ebfb7)  
---
### Add Birthday
  همچنین یک ویژگی دیگه اینکه می تونیم تاریخ تولد رو اضافه کنیم و موقع تولد هر کدوم از همکاران بهمون خبر میده و این فضا رو دوستانه تر می کنه :  

 ![Birthday](https://github.com/user-attachments/assets/3fa38586-208f-4e80-a823-6a5aaf7062da)  
---
### Manage Tasks
در قسمت مدیریت وظیفه ها امکانات خوبی مثل تقویم که می تونه تسک هامون رو نشون بده که برای چه روزی باید انجامشون بدیم ، بخش وظایف انجام شده روزانه که وظایف انجام شده رو نشون میده ، ایجاد دسته بندی برای کارها ، ایجاد برچسب :  

![ManageTasks](https://github.com/user-attachments/assets/493da8a0-3dc3-4a7f-87d6-349bb3c0fc8d)
---
### Manage Project
بخش مدیریت پروژه امکانات خیلی خوبی مثل ارتباط با همکارانی که در پروژه هستن از طریق گروه چتی که خودش ایجاد میکنه، ایجاد وظیفه، تقویم ، بورد،ایجاد جلسه آنلاین و درصد پیشرفت پروژه که یک نامی کلی بهمون نشون میده :   

![ManageProject](https://github.com/user-attachments/assets/c6bd69d2-3bbf-4a83-8aa5-dda8ade17319)

در قسمت بورد ها ما چند نوع تمپلیت داریم :  

![Board](https://github.com/user-attachments/assets/f7c335b2-298f-4739-893e-39155279e010)

مثلا میتونه کانبان باشه که لیست های برای انجام،در حال انجام ، انجام شده ایجاد می کنه یا می تونه واحد های سازمانی باشه مثلا بازاریابی،فروش،مالی یا می تونه اعضای تیم باشه و برای هر اعضا یک لیست ایجاد میشه ، یا می تونه روز های هفته باشه یا هم می تونه دلخواه باشه که خودمون اسم هاشون رو تعیین می کنیم.   

---
### Send Letter
سیستم ارسال نامه داره که خیلی خوبه و می تونیم با اعضای تیم ارتباط داشته باشیم :  

![SendLetter](https://github.com/user-attachments/assets/977f122a-8b75-44cb-bfa0-1e8741b8e99f)
---
### Notes
و یک بخشی داریم که می تونیم یادداشت های خودمون رو بنویسیم مثلا کارهای مهمی که داریم یادمون نره  :  

![notes](https://github.com/user-attachments/assets/a3e03301-7599-4f25-8139-bd271338d54b)
  
  ولی می تونست مثلا برای یادداشت هامون هم یک سیستم یادآوری قرار بده که مثلا کارهای مهم رو بتونیم یادآوری بکنیم.    
  
---
### Manage Customers
  یک ویژگی خیلی خوب دیگه ای که داره سیستم ایجاد مشتری و ارتباط با اونه می تونیم اطلاعات مشتری رو وارد کنیم و باهاش از طریق پیام در تماس باشیم:   

![manageCustomer](https://github.com/user-attachments/assets/e5433ad9-5c3a-452a-9faf-f42b050eb8ac)
---
### Monitoring 
و یک قسمت مانیتورینگ داره که مثلا می تونیم گزارش وضعیت مشتریان رو بگیریم :  

![reportCostomer](https://github.com/user-attachments/assets/75e41ba9-35e8-4c9e-a74a-0a930ab30be0)
  
یا می تونیم به صورت نمودار یادداشت های ایجاد شده ، وظلیف انجام شده  ، نامه ها ، گفت و گو ها و... رو ببینیم  :  

![monitoring](https://github.com/user-attachments/assets/d75d3d37-689c-4f76-8a95-261474da216a)
  
حتی قسمت مانیتورینگ اعضا هم وجود دارد :  

![ManageMembers](https://github.com/user-attachments/assets/33ec7f0c-7121-487d-937e-f20c9151bb33)
---
## Terminology
اصطلاحاتی که توی میزیو استفاده شده :  
  
1- میز کار : میزکار یک محیطی هست که تیم ما رو تشکیل میده و می تونیم اونجا پروژه هایی که گرفتیم و روش کار می کنیم و اعضا و.. رو مدیریت کنیم.  

2-وظیفه : همون تسک هست و می تونیم تسک ایجاد کنیم.  

3-نامه: می تونیم مثلا به اعضا نامه بنویسیم و باهاشون ارتباط داشته باشیم.   

4-یادداشت : می تونیم چیز هایی مهمی که داریم یادداشت کنیم تا یادمون نره.  

5-همکار : منظور اعضای تیم هستن که با هم همکارن.  

6-پرونده : منظور پرونده مشتری که از ما پروژه ای رو خواسته و می تونیم پروندشو ببینیم.  

7-بورد : یک نمای بورد مانند بهمون نشون میده که مثلا لیست کار های انجام شده ، در حال انجام و تمام شده می تونه باشه  مثل Github   Projects.    

8-مانیتورینگ : بخشیه که چیز های مختلف رو می تونیم گزارشش رو ببینیم مثل مانیتورینگ اعضا و مشتریان.  

9-کارتابل :  جایی که نامه هایی که به ما اومده رو می تونیم ببینیم.  

10-برچسب : می تونیم مثلا به تسک هامون برچسب بزنیم که فلان تسک مربوطه به مثلا تحقیق کردن.

**Comment by MirHosseinAmiriNotash** [comment]
[FA]

# Asena
آسنا یک ابزار مدیریت پروژه هست که میخوام اون رو بررسی بکنم و ببینیم که چه امکاناتی داره.  
## Login & Signup  
فرایند ثبت نام خیلی ساده هست فقط ایمیل از ما می خواد و وریفای کردن ایمیل و در ادامه اسم کاملمون و پسورد،می تونیم عکس پروفایل هم تعیین بکنیم یا نکنیم می تونیم اسم و ایمیل و وریفای کردنشو با گزینه Continue with Google رد کنیم و ساده تر هم بشه :  
  
![Signup](https://github.com/user-attachments/assets/d393e84c-0807-4c7c-934b-9f25e6b34055) 
  
![VerifyEmail](https://github.com/user-attachments/assets/ad289cb1-69d9-417a-9a52-fc6a4a8e7c81)
  
![EnterName   Pass](https://github.com/user-attachments/assets/469add8c-95ef-4685-98f9-a2f6489be65f) 

بعدش یک سری سوال در مورد حوزه فعالیتمون می پرسه که می تونیم skip بکنیم :  
  
![Skip](https://github.com/user-attachments/assets/b520ea3d-69e6-4e73-a8e9-b88426515864)   
  
![Skip2](https://github.com/user-attachments/assets/636ed250-ae01-4015-afb8-e2a3379664c0)
  
بعد باز هم یک سری سوال می پرسه که یک پروژه،تسک و... دیفالت بسازه که به نظرم یکم فرایند ثبت نام رو اینجا طولانی کرده از یه طرف دیگه شاید برای کسی که با این ابزار کار نکرده کارو براش ساده تر می کنه ولی می تونست برای این هم یک گزینه قرار بده که بشه Skip اش کرد :  
  
![Create Default Project](https://github.com/user-attachments/assets/08266076-2583-45aa-aefb-9717401096a9) 
  
![Create Default Project2](https://github.com/user-attachments/assets/7ee42b47-890a-40b8-af8f-2c8120880024) 

![Create Default Project3](https://github.com/user-attachments/assets/f80d4f0d-5bc7-46ee-b418-f3cfbf041b40)

![Create Default Project4](https://github.com/user-attachments/assets/616f9699-d679-4f26-8a4a-e2569ede223f)   
  
![Create Default Project5](https://github.com/user-attachments/assets/70f220f3-8e63-4933-8b5d-9c92288bfe21)  

بعد از اتمام ثبت نام می تونیم نمای کلی از محیط آسنا رو ببینیم :  
  
![FirstView](https://github.com/user-attachments/assets/6850aa78-dae6-42d6-938f-3ad16dffcb20) 
  
## UI
از لحاظ UI از محیط آسنا خوشم اومد می تونیم حتی روی darkmode هم بزاریم محیط خیلی ساده و خوبه حتی می تونیم رنگ بکگراند صفحه HOME رو عوض کنیم و شخصی سازی بکنیم و بهش حتی ویجت اضافه بکنیم  : 
  
![UI](https://github.com/user-attachments/assets/ef16b8fb-0470-44fe-9c07-e947875215c0) 
  
## UX  
می تونیم Notification ها رو شخصی سازی بکنیم مثلا از طریق مرورگر Notification دریافت بکنیم یا نه یا یه گزینه ای هست که اپلیکیشن موبایلشو دانلود بکنیم و روی موبایلمون Notification ها رو دریافت بکنیم و می تونیم به سرویس های مختلفی رو به آسنا لینک کنیم :  
  
![Notification](https://github.com/user-attachments/assets/2d1c1e8a-d8ae-49f9-ab16-78788f0cd648)  

   و می تونیم شخصی سازی بکنیم که مثلا کدوم اعلان از پروژه رو دریافت بکنیم و...  

![CustomNotification](https://github.com/user-attachments/assets/89c575e0-0bfe-4d9e-b478-6b06b3d53d96) 

همچنین دارک مود هم داریم :  

![Darkmode](https://github.com/user-attachments/assets/f91a5a36-fbc1-4bdb-92dd-137475487c88) 
  
همچنین یک بخشی هست که ویژگی های بیشتری رو به ما نشون میده و غیر فعال هستن وبر حسب نیاز می تونیم فعالشون کنیم مثلا غیر فعال کردن اعلان های مربوط به شروع تسک و...   
  
![extra](https://github.com/user-attachments/assets/a5dcb8b4-e8b4-4cd9-bf67-62fb52b1cccc)   

  وقتی پروژه ایجاد می کنیم می تونیم آیکون و رنگ پروژه رو تغییر بدیم :  

![Project icon](https://github.com/user-attachments/assets/46cc6fc2-dbd4-4fd1-be83-4b8ace0f0e12)  
  
## Features  
---  
### Create Task
ایجاد تسک ساده هست و فقط ازمون اسم تسک رو می خواد و می تونیم بهش مهلت انجام بدیم یا به یک پروژه مربوطش بکنیم و مثل Github Projects می تونیم به شکل لیست،بورد و تقویم تسک ها رو ببینیم و می تونیم لیست هایی ایجاد بکنیم که مثلا این تسک هفته بعد انجام خواهد شد :  
  
![AddTask](https://github.com/user-attachments/assets/71cd1643-19e2-4065-bc35-d8a95a101ab8)  
  
می تونیم برای تسک ها role تعریف بکنیم مثلا بگیم تسک اگر در لیست Do Next Week قرار گرفت بهش مهلت 5 روزه بده :  
  
![AddRole](https://github.com/user-attachments/assets/c1834fd8-a4d4-4b4e-888a-77256d19ec0e)
  
همچنین یک قسمت files داره که اگر فایلی قرار داده شده باشه اینجا نمایش داده میشه :  
  
![Files](https://github.com/user-attachments/assets/e97bf832-f54f-4061-bc73-1b410f08a55b) 

--- 
### Reporting
یک ویژگی دیگه ای که آسنا داره Reporting هست که انواع گزارش ها رو ما می تونیم داشته باشیم مثلا task per month داریم که همون Burndownchart هست که مدیر پروژه می تونه ببینه که تیمش در یک ماه چقدر تسک تونستن انجام بدن و بر اساس اون برنامه ریزی می کنه :  
  
![Report](https://github.com/user-attachments/assets/e8c663b2-d607-49a9-b60d-87ead743c620)

حتی می تونیم نمودار رو شخصی سازی بکنیم مثلا رنگ نمودار رو می تونیم عوض بکنیم ، برحسب ماهه پیشفرض مثلا بگیم بر حسب روز،سال و.. باشه ، یا می تونیم بگیم بر حسب تمام شدن تسک نباشه بر حسب مثلا ایجاد تسک باشه ، یا می تونیم بگیم بر حسب تعداد تسک نباشه بر حسب زمان تمام کردن تسک باشه، یا اصلا برحسب تسک نباشه بر حسب پروژه ، اهداف و.. باشه :  
  
![ReportSetting](https://github.com/user-attachments/assets/11fa628b-c68e-4f7a-a487-243e99367a9f) 
  
الان می تونیم نموداری که ایجاد کردیم ببینیم و می تونیم گزارش های دیگه ای هم اضافه بکنیم :  
  
![AddReport](https://github.com/user-attachments/assets/82fab04e-9a1f-4a5c-ab34-f642fd027c52) 

---  
### Create Project

ایجاد پروژه ساده هست و فقط نام پروژه رو از ما می خواد و می تونیم از تمپلیت های اماده ای که داره استفاه بکنیم :  

![createProject](https://github.com/user-attachments/assets/73426f7f-4dd2-4e78-a67f-0b25cde16909) 

![createProject2](https://github.com/user-attachments/assets/d31d35d2-e27b-4444-9fed-b43c9a0b8d67)
توی صفحه اول پروژه می تونیم نمای کلی رو ببینیم می تونیم توضیحاتی در مورد پروژه ببینیم اعضای پروژه رو ببینیم و اعضا اضافه بکنیم و... :  

![ProjectOverview](https://github.com/user-attachments/assets/22224018-b50e-4122-b5d8-79b9ea1c0a2f) 
  
می تونیم برای پروژه هدف ایجاد بکنیم :  

![Addgoal](https://github.com/user-attachments/assets/43aa8d62-f3df-4ab5-a308-c9498a9b3158)  
  
![Addgoal2](https://github.com/user-attachments/assets/00ff0623-844e-4333-9b2c-b1a4bd661722) 
  
همچنین می تونیم برای هدف وضعیت تعریف بکنیم درصد پیشرفتشو ببینیم و توضیحاتی در مورد هدف بنویسیم :  
  
![GoalOverview](https://github.com/user-attachments/assets/550c8d83-1ea6-412e-8bd2-586a4831f36f)  
  
  همین کار رو اگر بخوایم برای پروژه بکنیم یعنی بخوایم برای پروژه هدف ایجاد بکنیم از بخش نظیمات پروژه می تونیم هدفی که ایجاد کردیم رو لینک بکنیم به پروژه.  
      
همچنین می تونیم برای پروژه MileStone اضافه بکنیم :  

![MileStone](https://github.com/user-attachments/assets/1d9b8a39-f9cc-43e9-b2c6-b41cfd6394f0)  
  
  می تونیم یک گزارش کلی از تسک ها و.. در بخش داشبورد پروژه ببینیم :  
  
![ProjectDashboard](https://github.com/user-attachments/assets/85a9b816-6c56-4bef-8fe6-48faaf8edd5c)  
  
همچنین می تونیم برای پروژه Workflow تعریف بکنیم :  
  
![WorkFlow](https://github.com/user-attachments/assets/770250b8-1d28-46db-aa67-1d64b05aa069)  
  
بخش Message هم داریم که می تونیم با اعضای پروژه ارتباط داشته باشیم :  
  
![Message](https://github.com/user-attachments/assets/32ef6da3-ab5f-4b7f-b6f0-8584f2d1b20b)  
  
همچنین می تونیم به پروژه فایل اضافه بکنیم :  
  
![File](https://github.com/user-attachments/assets/47bc06c9-21f8-4cf2-8953-94845fb489fc) 
  
همچنین می تونیم به پروژه note، نمودار گانت و.. اضافه کنیم که در تصویر زیر می بینید :  
  
![ProjectExtra](https://github.com/user-attachments/assets/98c83408-3d3e-48a4-9df6-85b31e02dc26)   
  
---  
### Portfolios
در بخش Portfolios هم می تونیم چندین پروژه رو مدیریت بکنیم و می تونیم چندین پروژه رو عضو یک Portfolios بکنیم و وضعیتشون رو ببینیم و مدیریت بکنیم :  
  
![Portfolios](https://github.com/user-attachments/assets/7a95bb63-2ac9-46eb-8ac0-a2f90f130afb)  
  
![Portfolios2](https://github.com/user-attachments/assets/07a16bac-ee80-4188-abbd-53488810b2cf)  

  
---  
### Inbox

یک بخش inbox هم داریم که اعلان ها و پیام هایی که دریافت کردیم رو می تونیم ببینیم :  
  
![inbox](https://github.com/user-attachments/assets/12da0f56-42ad-4ac8-80d1-50d4c6efcb57)
  

## Terminology  
  
اصطلاحاتی که توی آسنا استفاده شده :  
  
1-Portfolios :  به ما این امکان را می دهد چندین پروژه را مدیریت بکنیم.  

2-Inbox: محل دریات اعلان و پیام ها   
 
3-Reporting:گزارش گیری  

4-Goals: اهداف  
  
5-Notes : یادداشت ها ی مهم که برای تیم ایجاد می کنیم.
